networks:
  default:
    external:
      name: library-management-system-network

version: "3"
services:
  db:
    image: postgres:14.5
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "username"
      POSTGRES_DB: "pgdatabase"

    ports:
      - "5435:5432"

  api:
    build:
      context: api
      dockerfile: dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - db
