FROM node:18.17.1

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

# RUN export NODE_ENV=production

# RUN npm run swagger-autogen

# CMD [ "npm", "run", "start" ]

COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]